name: document-synchronization
on: [push]
jobs:
  build-and-sync:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout -dev repository
        uses: actions/checkout@v2.3.4
        with:
          path: dev
      - name: Checkout -FDU repository
        uses: actions/checkout@v2.3.4
        with:
          repository: FDUCSLG/ICS-2021Spring-FDU
          ref: gh-pages
          token: ${{ secrets.DOC_SYNC }}
          persist-credentials: false
          fetch-depth: 0
          path: target
      - name: Install mdbook 0.4.7
        uses: actions-rs/install@v0.1
        with:
          crate: mdbook
          version: 0.4.7
          use-tool-cache: true
      - name: Install mdbook-katex 0.2.8
        uses: actions-rs/install@v0.1
        with:
          crate: mdbook-katex
          version: 0.2.8
          use-tool-cache: true
      - name: mdBook build
        working-directory: ./dev/doc
        run: mdbook build
      - name: Copy output files
        run: cp -r ./dev/doc/book ./target/docs
      - name: Commit to gh-pages
        working-directory: ./target
        run: |
          git config --local user.email "riteme@qq.com"
          git config --local user.name "riteme"
          git add -A
          git commit -m "Update docs."
      - name: Push to gh-pages
        uses: ad-m/github-push-action@v0.6.0
        with:
          directory: ./target
          github_token: ${{ secrets.DOC_SYNC }}
          repository: FDUCSLG/ICS-2021Spring-FDU
          branch: gh-pages
