name: ubuntu-20.04-test
on:
  push:
    branches:
      - master
      - sync
jobs:
  setup:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout -dev repository
        uses: actions/checkout@v2.3.4
      - name: Install prerequisites
        run: |
          sudo apt update
          sudo apt install -y verilator gtkwave build-essential libz-dev
  functional-test:
    runs-on: ubuntu-20.04
    needs: setup
    steps:
      - name: Run NSCSCC functional tests
        run: make vsim -j
  performance-test:
    runs-on: ubuntu-20.04
    needs: setup
    steps:
      - name: Run NSCSCC performance tests
        run: make vsim -j VSIM_ARGS='--force-diff -m "./misc/nscscc/coremark.coe" -r "./misc/std/coremark.txt"'
